-- Lais Imob Pro v1.0 | CORRECAO FINAL SQL v2
-- Rode este arquivo único no Supabase SQL Editor.
-- Ele não apaga dados. Ele repara colunas ausentes, recria RPCs e aplica a camada de produção.


-- ============================================================
-- HOTFIX v2: reparar colunas ausentes em tabelas já existentes
-- Segurança: não apaga tabelas nem dados. Apenas adiciona colunas ausentes.
-- Motivo: CREATE TABLE IF NOT EXISTS não atualiza tabelas antigas/incompletas.
-- ============================================================

create extension if not exists pgcrypto;

-- 0) Derruba somente RPCs/funções do projeto, independentemente da assinatura antiga.
do $$
declare
  r record;
begin
  for r in
    select p.oid::regprocedure::text as fn
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.proname in (
        'imobagent_20260504_ready_upsert_customer',
        'imobagent_20260504_ready_conversation_snapshot',
        'imobagent_20260504_ready_enqueue_handoff',
        'imobagent_20260504_ready_write_outcome',
        'imobagent_20260504_ready_commit_book',
        'imobagent_20260504_ready_commit_reschedule',
        'imobagent_20260504_ready_commit_cancel',
        'imobagent_20260504_ready_upsert_lead_crm',
        'imobagent_20260504_ready_admin_summary_today_realty',
        'imobagent_20260504_ready_admin_summary_week_realty',
        'imobagent_20260504_ready_admin_operational_alerts',
        'imobagent_20260504_ready_admin_followup_queue',
        'imobagent_try_register_inbound',
        'imobagent_try_register_outbound',
        'imobagent_20260504_ready_acquire_slot_lock',
        'imobagent_20260504_ready_release_slot_lock',
        'imobagent_20260504_ready_record_seller_command',
        'imobagent_20260504_ready_catalog_export',
        'imobagent_20260504_ready_log_error'
      )
  loop
    execute 'drop function if exists ' || r.fn;
  end loop;
end $$;

-- 1) Reparos da base principal
alter table if exists public.imobagent_20260504_ready_runtime_config
  add column if not exists tenant_id text default 'default',
  add column if not exists config jsonb not null default '{}'::jsonb,
  add column if not exists config_version text not null default 'embedded',
  add column if not exists updated_at timestamptz not null default now();

alter table if exists public.imobagent_20260504_ready_customers
  add column if not exists tenant_id text not null default 'default',
  add column if not exists phone_e164 text,
  add column if not exists display_name text,
  add column if not exists whatsapp_name text,
  add column if not exists customer_phone text,
  add column if not exists contact_id text,
  add column if not exists contact_key text,
  add column if not exists channel text default 'whatsapp',
  add column if not exists runtime_state jsonb not null default '{}'::jsonb,
  add column if not exists pending_context jsonb not null default '{}'::jsonb,
  add column if not exists last_stage text,
  add column if not exists last_action text,
  add column if not exists last_status text,
  add column if not exists last_inbound_text text,
  add column if not exists last_outbound_text text,
  add column if not exists last_inbound_at timestamptz,
  add column if not exists last_outbound_at timestamptz,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

alter table if exists public.imobagent_20260504_ready_conversation_events
  add column if not exists event_id bigint generated by default as identity,
  add column if not exists tenant_id text not null default 'default',
  add column if not exists phone_e164 text,
  add column if not exists direction text not null default 'system',
  add column if not exists stage text,
  add column if not exists action text,
  add column if not exists status text,
  add column if not exists inbound_text text,
  add column if not exists outbound_text text,
  add column if not exists protocol text,
  add column if not exists pending_context jsonb not null default '{}'::jsonb,
  add column if not exists metadata jsonb not null default '{}'::jsonb,
  add column if not exists created_at timestamptz not null default now();

alter table if exists public.imobagent_20260504_ready_handoffs
  add column if not exists handoff_id bigint generated by default as identity,
  add column if not exists tenant_id text not null default 'default',
  add column if not exists phone_e164 text,
  add column if not exists reason text,
  add column if not exists summary text,
  add column if not exists payload jsonb not null default '{}'::jsonb,
  add column if not exists status text not null default 'queued',
  add column if not exists accepted_at timestamptz,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

alter table if exists public.imobagent_20260504_ready_appointments
  add column if not exists tenant_id text not null default 'default',
  add column if not exists appointment_id text,
  add column if not exists phone_e164 text,
  add column if not exists customer_name text,
  add column if not exists calendar_id text,
  add column if not exists calendar_event_id text,
  add column if not exists service_key text,
  add column if not exists service_label text,
  add column if not exists date_br text,
  add column if not exists time_hhmm text,
  add column if not exists start_at timestamptz,
  add column if not exists end_at timestamptz,
  add column if not exists status text not null default 'booked',
  add column if not exists lead_score numeric,
  add column if not exists lead_category text,
  add column if not exists metadata jsonb not null default '{}'::jsonb,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

alter table if exists public.imobagent_20260504_ready_lead_crm
  add column if not exists tenant_id text not null default 'default',
  add column if not exists phone_e164 text,
  add column if not exists customer_name text,
  add column if not exists customer_phone text,
  add column if not exists contact_id text,
  add column if not exists interest_type text,
  add column if not exists lead_stage text,
  add column if not exists lead_temperature text,
  add column if not exists lead_score numeric,
  add column if not exists desired_property_type text,
  add column if not exists desired_city text,
  add column if not exists desired_neighborhoods jsonb not null default '[]'::jsonb,
  add column if not exists desired_bedrooms numeric,
  add column if not exists desired_parking numeric,
  add column if not exists budget_max numeric,
  add column if not exists monthly_income numeric,
  add column if not exists payment_mode text,
  add column if not exists financing_needed boolean,
  add column if not exists fgts_available boolean,
  add column if not exists estimated_down_payment numeric,
  add column if not exists urgency text,
  add column if not exists pain_point text,
  add column if not exists objections jsonb,
  add column if not exists matched_listings jsonb not null default '[]'::jsonb,
  add column if not exists favorite_listing text,
  add column if not exists visit_interest boolean,
  add column if not exists visit_status text,
  add column if not exists seller_owner text,
  add column if not exists assigned_seller jsonb,
  add column if not exists handoff_status text,
  add column if not exists next_best_action text,
  add column if not exists conversation_summary text,
  add column if not exists seller_summary text,
  add column if not exists last_inbound_text text,
  add column if not exists last_outbound_text text,
  add column if not exists last_inbound_at timestamptz,
  add column if not exists last_outbound_at timestamptz,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

-- 2) Reparos da camada de produção complementar
alter table if exists public.imobagent_inbound_idempotency
  add column if not exists id uuid default gen_random_uuid(),
  add column if not exists tenant_id text not null default 'default',
  add column if not exists idempotency_key text,
  add column if not exists contact_key text,
  add column if not exists message_uid text,
  add column if not exists payload jsonb not null default '{}'::jsonb,
  add column if not exists created_at timestamptz not null default now();

alter table if exists public.imobagent_outbound_idempotency
  add column if not exists id uuid default gen_random_uuid(),
  add column if not exists tenant_id text not null default 'default',
  add column if not exists idempotency_key text,
  add column if not exists contact_key text,
  add column if not exists channel text default 'whatsapp',
  add column if not exists outbound_text text,
  add column if not exists provider_response jsonb not null default '{}'::jsonb,
  add column if not exists created_at timestamptz not null default now();

alter table if exists public.imobagent_20260504_ready_slot_locks
  add column if not exists lock_id uuid default gen_random_uuid(),
  add column if not exists tenant_id text not null default 'default',
  add column if not exists slot_key text,
  add column if not exists calendar_id text,
  add column if not exists start_at timestamptz,
  add column if not exists end_at timestamptz,
  add column if not exists phone_e164 text,
  add column if not exists service_key text,
  add column if not exists action text default 'book',
  add column if not exists idempotency_key text,
  add column if not exists trace_id text,
  add column if not exists lock_token text not null default encode(gen_random_bytes(18), 'hex'),
  add column if not exists status text not null default 'locked',
  add column if not exists expires_at timestamptz not null default now() + interval '10 minutes',
  add column if not exists metadata jsonb not null default '{}'::jsonb,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

alter table if exists public.imobagent_20260504_ready_seller_commands
  add column if not exists command_id bigint generated by default as identity,
  add column if not exists tenant_id text not null default 'default',
  add column if not exists phone_e164 text,
  add column if not exists command text,
  add column if not exists status text default 'received',
  add column if not exists payload jsonb not null default '{}'::jsonb,
  add column if not exists created_at timestamptz not null default now();

alter table if exists public.imobagent_20260504_ready_operational_errors
  add column if not exists error_id bigint generated by default as identity,
  add column if not exists tenant_id text not null default 'default',
  add column if not exists workflow_name text,
  add column if not exists execution_id text,
  add column if not exists node_name text,
  add column if not exists error_message text,
  add column if not exists payload jsonb not null default '{}'::jsonb,
  add column if not exists created_at timestamptz not null default now();

-- 3) Constraints reais para ON CONFLICT serão tentadas no bloco abaixo.

create unique index if not exists imobagent_outbound_idempotency_tenant_key_uq
  on public.imobagent_outbound_idempotency (tenant_id, idempotency_key)
  where idempotency_key is not null;



-- 4) Tentativa segura de constraints reais para ON CONFLICT.
-- Se houver duplicados antigos, o bloco não interrompe a instalação; apenas mantém os índices auxiliares.
do $$
begin
  begin
    if to_regclass('public.imobagent_20260504_ready_customers') is not null
       and not exists (select 1 from pg_constraint where conname = 'imobagent_ready_customers_tenant_phone_key') then
      alter table public.imobagent_20260504_ready_customers
        add constraint imobagent_ready_customers_tenant_phone_key unique (tenant_id, phone_e164);
    end if;
  exception when others then
    raise notice 'Aviso: não foi possível criar unique em customers: %', sqlerrm;
  end;

  begin
    if to_regclass('public.imobagent_20260504_ready_appointments') is not null
       and not exists (select 1 from pg_constraint where conname = 'imobagent_ready_appointments_tenant_appointment_key') then
      alter table public.imobagent_20260504_ready_appointments
        add constraint imobagent_ready_appointments_tenant_appointment_key unique (tenant_id, appointment_id);
    end if;
  exception when others then
    raise notice 'Aviso: não foi possível criar unique em appointments: %', sqlerrm;
  end;

  begin
    if to_regclass('public.imobagent_20260504_ready_lead_crm') is not null
       and not exists (select 1 from pg_constraint where conname = 'imobagent_ready_lead_crm_tenant_phone_key') then
      alter table public.imobagent_20260504_ready_lead_crm
        add constraint imobagent_ready_lead_crm_tenant_phone_key unique (tenant_id, phone_e164);
    end if;
  exception when others then
    raise notice 'Aviso: não foi possível criar unique em lead_crm: %', sqlerrm;
  end;

  begin
    if to_regclass('public.imobagent_inbound_idempotency') is not null
       and not exists (select 1 from pg_constraint where conname = 'imobagent_inbound_idempotency_tenant_key_key') then
      alter table public.imobagent_inbound_idempotency
        add constraint imobagent_inbound_idempotency_tenant_key_key unique (tenant_id, idempotency_key);
    end if;
  exception when others then
    raise notice 'Aviso: não foi possível criar unique em inbound_idempotency: %', sqlerrm;
  end;

  begin
    if to_regclass('public.imobagent_outbound_idempotency') is not null
       and not exists (select 1 from pg_constraint where conname = 'imobagent_outbound_idempotency_tenant_key_key') then
      alter table public.imobagent_outbound_idempotency
        add constraint imobagent_outbound_idempotency_tenant_key_key unique (tenant_id, idempotency_key);
    end if;
  exception when others then
    raise notice 'Aviso: não foi possível criar unique em outbound_idempotency: %', sqlerrm;
  end;
end $$;


-- ============================================================
-- SQL BASE ORIGINAL SEGURO
-- ============================================================

-- ImobAgent Pro | SQL opcional seguro e não destrutivo
-- Escopo: somente objetos com prefixo imobagent_20260504_ready_*.
-- Não usa comandos destrutivos nem altera objetos de outros fluxos.
-- Execute no Supabase SQL Editor se as tabelas/RPCs ainda não existirem.

create table if not exists public.imobagent_20260504_ready_runtime_config (
  tenant_id text primary key default 'default',
  config jsonb not null default '{}'::jsonb,
  config_version text not null default 'embedded',
  updated_at timestamptz not null default now()
);

create table if not exists public.imobagent_20260504_ready_customers (
  tenant_id text not null default 'default',
  phone_e164 text not null,
  display_name text,
  whatsapp_name text,
  customer_phone text,
  contact_id text,
  contact_key text,
  channel text default 'whatsapp',
  runtime_state jsonb not null default '{}'::jsonb,
  pending_context jsonb not null default '{}'::jsonb,
  last_stage text,
  last_action text,
  last_status text,
  last_inbound_text text,
  last_outbound_text text,
  last_inbound_at timestamptz,
  last_outbound_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (tenant_id, phone_e164)
);

create table if not exists public.imobagent_20260504_ready_conversation_events (
  event_id bigint generated by default as identity primary key,
  tenant_id text not null default 'default',
  phone_e164 text,
  direction text not null default 'system',
  stage text,
  action text,
  status text,
  inbound_text text,
  outbound_text text,
  protocol text,
  pending_context jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.imobagent_20260504_ready_handoffs (
  handoff_id bigint generated by default as identity primary key,
  tenant_id text not null default 'default',
  phone_e164 text,
  reason text,
  summary text,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'queued',
  accepted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.imobagent_20260504_ready_appointments (
  tenant_id text not null default 'default',
  appointment_id text not null,
  phone_e164 text,
  customer_name text,
  calendar_id text,
  calendar_event_id text,
  service_key text,
  service_label text,
  date_br text,
  time_hhmm text,
  start_at timestamptz,
  end_at timestamptz,
  status text not null default 'booked',
  lead_score numeric,
  lead_category text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (tenant_id, appointment_id)
);

create table if not exists public.imobagent_20260504_ready_lead_crm (
  tenant_id text not null default 'default',
  phone_e164 text not null,
  customer_name text,
  customer_phone text,
  contact_id text,
  interest_type text,
  lead_stage text,
  lead_temperature text,
  lead_score numeric,
  desired_property_type text,
  desired_city text,
  desired_neighborhoods jsonb not null default '[]'::jsonb,
  desired_bedrooms numeric,
  desired_parking numeric,
  budget_max numeric,
  monthly_income numeric,
  payment_mode text,
  financing_needed boolean,
  fgts_available boolean,
  estimated_down_payment numeric,
  urgency text,
  pain_point text,
  objections jsonb,
  matched_listings jsonb not null default '[]'::jsonb,
  favorite_listing text,
  visit_interest boolean,
  visit_status text,
  seller_owner text,
  assigned_seller jsonb,
  handoff_status text,
  next_best_action text,
  conversation_summary text,
  seller_summary text,
  last_inbound_text text,
  last_outbound_text text,
  last_inbound_at timestamptz,
  last_outbound_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (tenant_id, phone_e164)
);

create index if not exists imobagent_20260504_ready_events_tenant_created_idx
  on public.imobagent_20260504_ready_conversation_events (tenant_id, created_at desc);

create index if not exists imobagent_20260504_ready_handoffs_tenant_status_idx
  on public.imobagent_20260504_ready_handoffs (tenant_id, status, created_at desc);

create index if not exists imobagent_20260504_ready_appointments_tenant_status_idx
  on public.imobagent_20260504_ready_appointments (tenant_id, status, start_at desc);

create index if not exists imobagent_20260504_ready_lead_crm_tenant_updated_idx
  on public.imobagent_20260504_ready_lead_crm (tenant_id, updated_at desc);

create or replace function public.imobagent_20260504_ready_upsert_customer(
  p_phone_e164 text,
  p_display_name text default null,
  p_whatsapp_name text default null,
  p_last_inbound_text text default null,
  p_tenant_id text default 'default'
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tenant text := coalesce(nullif(p_tenant_id, ''), 'default');
  v_phone text := nullif(p_phone_e164, '');
  v_row public.imobagent_20260504_ready_customers%rowtype;
begin
  if v_phone is null then
    return jsonb_build_object('ok', false, 'reason', 'missing_phone_e164');
  end if;

  insert into public.imobagent_20260504_ready_customers (
    tenant_id, phone_e164, display_name, whatsapp_name, customer_phone,
    last_inbound_text, last_inbound_at, updated_at
  ) values (
    v_tenant, v_phone, nullif(p_display_name, ''), nullif(p_whatsapp_name, ''), regexp_replace(v_phone, '[^0-9]', '', 'g'),
    nullif(p_last_inbound_text, ''), now(), now()
  )
  on conflict (tenant_id, phone_e164) do update set
    display_name = coalesce(excluded.display_name, public.imobagent_20260504_ready_customers.display_name),
    whatsapp_name = coalesce(excluded.whatsapp_name, public.imobagent_20260504_ready_customers.whatsapp_name),
    customer_phone = coalesce(excluded.customer_phone, public.imobagent_20260504_ready_customers.customer_phone),
    last_inbound_text = coalesce(excluded.last_inbound_text, public.imobagent_20260504_ready_customers.last_inbound_text),
    last_inbound_at = now(),
    updated_at = now()
  returning * into v_row;

  insert into public.imobagent_20260504_ready_conversation_events (
    tenant_id, phone_e164, direction, inbound_text, metadata
  ) values (
    v_tenant, v_phone, 'inbound', nullif(p_last_inbound_text, ''), jsonb_build_object('source', 'upsert_customer')
  );

  return jsonb_build_object(
    'ok', true,
    'tenant_id', v_row.tenant_id,
    'phone_e164', v_row.phone_e164,
    'customer_name', coalesce(v_row.display_name, v_row.whatsapp_name),
    'runtime_state', v_row.runtime_state,
    'pending_context', v_row.pending_context
  );
end;
$$;

create or replace function public.imobagent_20260504_ready_conversation_snapshot(
  p_phone_e164 text,
  p_tenant_id text default 'default'
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tenant text := coalesce(nullif(p_tenant_id, ''), 'default');
  v_phone text := nullif(p_phone_e164, '');
  v_customer public.imobagent_20260504_ready_customers%rowtype;
  v_recent jsonb;
  v_appointments jsonb;
begin
  if v_phone is null then
    return jsonb_build_object('phone_e164', null, 'pending_context', '{}'::jsonb, 'recent_context', '[]'::jsonb, 'active_appointments', '[]'::jsonb);
  end if;

  select * into v_customer
  from public.imobagent_20260504_ready_customers
  where tenant_id = v_tenant and phone_e164 = v_phone;

  select coalesce(jsonb_agg(to_jsonb(e) order by e.created_at desc), '[]'::jsonb)
  into v_recent
  from (
    select stage, action, status, inbound_text, outbound_text, protocol, pending_context, created_at
    from public.imobagent_20260504_ready_conversation_events
    where tenant_id = v_tenant and phone_e164 = v_phone
    order by created_at desc
    limit 8
  ) e;

  select coalesce(jsonb_agg(to_jsonb(a) order by a.start_at desc), '[]'::jsonb)
  into v_appointments
  from (
    select appointment_id, calendar_event_id, service_key, service_label, date_br, time_hhmm, start_at, end_at, status
    from public.imobagent_20260504_ready_appointments
    where tenant_id = v_tenant and phone_e164 = v_phone and status in ('booked', 'rescheduled', 'confirmed', 'confirmed_24h')
    order by start_at desc nulls last
    limit 5
  ) a;

  return jsonb_build_object(
    'tenant_id', v_tenant,
    'phone_e164', v_phone,
    'customer_phone', regexp_replace(v_phone, '[^0-9]', '', 'g'),
    'customer_name', coalesce(v_customer.display_name, v_customer.whatsapp_name),
    'runtime_state', coalesce(v_customer.runtime_state, '{}'::jsonb),
    'pending_context', coalesce(v_customer.pending_context, '{}'::jsonb),
    'recent_context', coalesce(v_recent, '[]'::jsonb),
    'active_appointments', coalesce(v_appointments, '[]'::jsonb),
    'last_bot_text', v_customer.last_outbound_text,
    'last_outbound_text', v_customer.last_outbound_text,
    'stage', v_customer.last_stage,
    'status', v_customer.last_status
  );
end;
$$;

create or replace function public.imobagent_20260504_ready_enqueue_handoff(
  p_phone_e164 text,
  p_reason text default null,
  p_summary text default null,
  p_payload jsonb default '{}'::jsonb,
  p_tenant_id text default 'default'
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tenant text := coalesce(nullif(p_tenant_id, ''), 'default');
  v_phone text := nullif(p_phone_e164, '');
  v_id bigint;
begin
  insert into public.imobagent_20260504_ready_handoffs (
    tenant_id, phone_e164, reason, summary, payload, status, updated_at
  ) values (
    v_tenant, v_phone, coalesce(nullif(p_reason, ''), 'solicitacao_humana'), p_summary, coalesce(p_payload, '{}'::jsonb), 'queued', now()
  ) returning handoff_id into v_id;

  if v_phone is not null then
    update public.imobagent_20260504_ready_customers
    set last_status = 'awaiting_seller',
        pending_context = coalesce(p_payload->'pending_context', pending_context),
        updated_at = now()
    where tenant_id = v_tenant and phone_e164 = v_phone;
  end if;

  insert into public.imobagent_20260504_ready_conversation_events (
    tenant_id, phone_e164, direction, stage, action, status, outbound_text, pending_context, metadata
  ) values (
    v_tenant, v_phone, 'system', 'handoff', 'HANDOFF', 'queued', p_summary,
    coalesce(p_payload->'pending_context', '{}'::jsonb), jsonb_build_object('handoff_id', v_id, 'reason', p_reason)
  );

  return jsonb_build_object('ok', true, 'handoff_id', v_id, 'status', 'queued');
end;
$$;

create or replace function public.imobagent_20260504_ready_write_outcome(
  p_phone_e164 text,
  p_tenant_id text default 'default',
  p_stage text default null,
  p_action text default null,
  p_status text default null,
  p_inbound_text text default null,
  p_outbound_text text default null,
  p_protocol text default null,
  p_pending_context jsonb default '{}'::jsonb
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tenant text := coalesce(nullif(p_tenant_id, ''), 'default');
  v_phone text := nullif(p_phone_e164, '');
  v_pending jsonb := coalesce(p_pending_context, '{}'::jsonb);
  v_state jsonb;
begin
  if v_phone is null then
    return jsonb_build_object('ok', false, 'reason', 'missing_phone_e164');
  end if;

  v_state := jsonb_build_object(
    'stage', p_stage,
    'action', p_action,
    'status', p_status,
    'pending_context', v_pending,
    'protocol', p_protocol,
    'last_bot_text', p_outbound_text,
    'last_outbound_text', p_outbound_text,
    'updated_at', now()
  );

  insert into public.imobagent_20260504_ready_customers (
    tenant_id, phone_e164, customer_phone, runtime_state, pending_context,
    last_stage, last_action, last_status, last_inbound_text, last_outbound_text,
    last_inbound_at, last_outbound_at, updated_at
  ) values (
    v_tenant, v_phone, regexp_replace(v_phone, '[^0-9]', '', 'g'), v_state, v_pending,
    p_stage, p_action, p_status, p_inbound_text, p_outbound_text,
    case when p_inbound_text is not null then now() else null end,
    case when p_outbound_text is not null then now() else null end,
    now()
  )
  on conflict (tenant_id, phone_e164) do update set
    runtime_state = coalesce(public.imobagent_20260504_ready_customers.runtime_state, '{}'::jsonb) || excluded.runtime_state,
    pending_context = excluded.pending_context,
    last_stage = excluded.last_stage,
    last_action = excluded.last_action,
    last_status = excluded.last_status,
    last_inbound_text = coalesce(excluded.last_inbound_text, public.imobagent_20260504_ready_customers.last_inbound_text),
    last_outbound_text = coalesce(excluded.last_outbound_text, public.imobagent_20260504_ready_customers.last_outbound_text),
    last_inbound_at = coalesce(excluded.last_inbound_at, public.imobagent_20260504_ready_customers.last_inbound_at),
    last_outbound_at = coalesce(excluded.last_outbound_at, public.imobagent_20260504_ready_customers.last_outbound_at),
    updated_at = now();

  insert into public.imobagent_20260504_ready_conversation_events (
    tenant_id, phone_e164, direction, stage, action, status, inbound_text, outbound_text, protocol, pending_context
  ) values (
    v_tenant, v_phone, 'outcome', p_stage, p_action, p_status, p_inbound_text, p_outbound_text, p_protocol, v_pending
  );

  return jsonb_build_object('ok', true, 'stage', p_stage, 'status', p_status, 'protocol', p_protocol);
end;
$$;

create or replace function public.imobagent_20260504_ready_commit_book(
  p_slot_key text default null,
  p_event_id text default null,
  p_phone_e164 text default null,
  p_customer_name text default null,
  p_calendar_id text default null,
  p_service_key text default null,
  p_service_label text default null,
  p_date_br text default null,
  p_time_hhmm text default null,
  p_start_at timestamptz default null,
  p_end_at timestamptz default null,
  p_lead_score numeric default null,
  p_lead_category text default null,
  p_tenant_id text default 'default',
  p_trace_id text default null,
  p_idempotency_key text default null,
  p_lock_token text default null,
  p_release_lock boolean default true
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tenant text := coalesce(nullif(p_tenant_id, ''), 'default');
  v_appt_id text := coalesce(nullif(p_idempotency_key, ''), nullif(p_event_id, ''), 'appt_' || md5(coalesce(p_phone_e164,'') || coalesce(p_service_key,'') || coalesce(p_start_at::text, now()::text)));
begin
  insert into public.imobagent_20260504_ready_appointments (
    tenant_id, appointment_id, phone_e164, customer_name, calendar_id, calendar_event_id,
    service_key, service_label, date_br, time_hhmm, start_at, end_at, status,
    lead_score, lead_category, metadata, updated_at
  ) values (
    v_tenant, v_appt_id, p_phone_e164, p_customer_name, p_calendar_id, p_event_id,
    p_service_key, p_service_label, p_date_br, p_time_hhmm, p_start_at, p_end_at, 'booked',
    p_lead_score, p_lead_category, jsonb_build_object('slot_key', p_slot_key, 'trace_id', p_trace_id, 'lock_token', p_lock_token), now()
  )
  on conflict (tenant_id, appointment_id) do update set
    calendar_event_id = coalesce(excluded.calendar_event_id, public.imobagent_20260504_ready_appointments.calendar_event_id),
    status = 'booked',
    start_at = coalesce(excluded.start_at, public.imobagent_20260504_ready_appointments.start_at),
    end_at = coalesce(excluded.end_at, public.imobagent_20260504_ready_appointments.end_at),
    updated_at = now();

  return jsonb_build_object('ok', true, 'appointment_id', v_appt_id, 'status', 'booked');
end;
$$;

create or replace function public.imobagent_20260504_ready_commit_reschedule(
  p_slot_key text default null,
  p_old_event_id text default null,
  p_new_event_id text default null,
  p_phone_e164 text default null,
  p_customer_name text default null,
  p_calendar_id text default null,
  p_service_key text default null,
  p_service_label text default null,
  p_date_br text default null,
  p_time_hhmm text default null,
  p_start_at timestamptz default null,
  p_end_at timestamptz default null,
  p_tenant_id text default 'default',
  p_trace_id text default null,
  p_idempotency_key text default null,
  p_lock_token text default null,
  p_release_lock boolean default true,
  p_delete_old_success boolean default null,
  p_delete_old_error text default null
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tenant text := coalesce(nullif(p_tenant_id, ''), 'default');
  v_appt_id text := coalesce(nullif(p_idempotency_key, ''), nullif(p_new_event_id, ''), 'res_' || md5(coalesce(p_phone_e164,'') || coalesce(p_service_key,'') || coalesce(p_start_at::text, now()::text)));
begin
  if p_old_event_id is not null then
    update public.imobagent_20260504_ready_appointments
    set status = 'rescheduled_old', updated_at = now()
    where tenant_id = v_tenant and (calendar_event_id = p_old_event_id or appointment_id = p_old_event_id);
  end if;

  insert into public.imobagent_20260504_ready_appointments (
    tenant_id, appointment_id, phone_e164, customer_name, calendar_id, calendar_event_id,
    service_key, service_label, date_br, time_hhmm, start_at, end_at, status, metadata, updated_at
  ) values (
    v_tenant, v_appt_id, p_phone_e164, p_customer_name, p_calendar_id, p_new_event_id,
    p_service_key, p_service_label, p_date_br, p_time_hhmm, p_start_at, p_end_at, 'rescheduled',
    jsonb_build_object('slot_key', p_slot_key, 'old_event_id', p_old_event_id, 'trace_id', p_trace_id, 'delete_old_success', p_delete_old_success, 'delete_old_error', p_delete_old_error), now()
  )
  on conflict (tenant_id, appointment_id) do update set
    calendar_event_id = coalesce(excluded.calendar_event_id, public.imobagent_20260504_ready_appointments.calendar_event_id),
    status = 'rescheduled',
    start_at = coalesce(excluded.start_at, public.imobagent_20260504_ready_appointments.start_at),
    end_at = coalesce(excluded.end_at, public.imobagent_20260504_ready_appointments.end_at),
    updated_at = now();

  return jsonb_build_object('ok', true, 'appointment_id', v_appt_id, 'status', 'rescheduled');
end;
$$;

create or replace function public.imobagent_20260504_ready_commit_cancel(
  p_old_event_id text default null,
  p_phone_e164 text default null,
  p_provider_deleted boolean default null,
  p_delete_error text default null,
  p_tenant_id text default 'default'
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tenant text := coalesce(nullif(p_tenant_id, ''), 'default');
  v_appt_id text := coalesce(nullif(p_old_event_id, ''), 'cancel_' || md5(coalesce(p_phone_e164,'') || now()::text));
begin
  update public.imobagent_20260504_ready_appointments
  set status = 'cancelled', metadata = metadata || jsonb_build_object('provider_deleted', p_provider_deleted, 'delete_error', p_delete_error), updated_at = now()
  where tenant_id = v_tenant and (appointment_id = v_appt_id or calendar_event_id = p_old_event_id or appointment_id = p_old_event_id);

  return jsonb_build_object('ok', true, 'appointment_id', v_appt_id, 'status', 'cancelled', 'provider_deleted', coalesce(p_provider_deleted, false));
end;
$$;

create or replace function public.imobagent_20260504_ready_upsert_lead_crm(
  p_tenant_id text default 'default',
  p_phone_e164 text default null,
  p_customer_name text default null,
  p_customer_phone text default null,
  p_contact_id text default null,
  p_interest_type text default null,
  p_lead_stage text default null,
  p_lead_temperature text default null,
  p_lead_score numeric default null,
  p_desired_property_type text default null,
  p_desired_city text default null,
  p_desired_neighborhoods jsonb default '[]'::jsonb,
  p_desired_bedrooms numeric default null,
  p_desired_parking numeric default null,
  p_budget_max numeric default null,
  p_monthly_income numeric default null,
  p_payment_mode text default null,
  p_financing_needed boolean default null,
  p_fgts_available boolean default null,
  p_estimated_down_payment numeric default null,
  p_urgency text default null,
  p_pain_point text default null,
  p_objections jsonb default null,
  p_matched_listings jsonb default '[]'::jsonb,
  p_favorite_listing text default null,
  p_visit_interest boolean default null,
  p_visit_status text default null,
  p_seller_owner text default null,
  p_assigned_seller jsonb default null,
  p_handoff_status text default null,
  p_next_best_action text default null,
  p_conversation_summary text default null,
  p_seller_summary text default null,
  p_last_inbound_text text default null,
  p_last_outbound_text text default null
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tenant text := coalesce(nullif(p_tenant_id, ''), 'default');
  v_phone text := nullif(p_phone_e164, '');
begin
  if v_phone is null then
    return jsonb_build_object('ok', false, 'reason', 'missing_phone_e164');
  end if;

  insert into public.imobagent_20260504_ready_lead_crm (
    tenant_id, phone_e164, customer_name, customer_phone, contact_id, interest_type,
    lead_stage, lead_temperature, lead_score, desired_property_type, desired_city,
    desired_neighborhoods, desired_bedrooms, desired_parking, budget_max, monthly_income,
    payment_mode, financing_needed, fgts_available, estimated_down_payment, urgency,
    pain_point, objections, matched_listings, favorite_listing, visit_interest, visit_status,
    seller_owner, assigned_seller, handoff_status, next_best_action, conversation_summary,
    seller_summary, last_inbound_text, last_outbound_text, last_inbound_at, last_outbound_at, updated_at
  ) values (
    v_tenant, v_phone, p_customer_name, p_customer_phone, p_contact_id, p_interest_type,
    p_lead_stage, p_lead_temperature, p_lead_score, p_desired_property_type, p_desired_city,
    coalesce(p_desired_neighborhoods, '[]'::jsonb), p_desired_bedrooms, p_desired_parking, p_budget_max, p_monthly_income,
    p_payment_mode, p_financing_needed, p_fgts_available, p_estimated_down_payment, p_urgency,
    p_pain_point, p_objections, coalesce(p_matched_listings, '[]'::jsonb), p_favorite_listing, p_visit_interest, p_visit_status,
    p_seller_owner, p_assigned_seller, p_handoff_status, p_next_best_action, p_conversation_summary,
    p_seller_summary, p_last_inbound_text, p_last_outbound_text,
    case when p_last_inbound_text is not null then now() else null end,
    case when p_last_outbound_text is not null then now() else null end,
    now()
  )
  on conflict (tenant_id, phone_e164) do update set
    customer_name = coalesce(excluded.customer_name, public.imobagent_20260504_ready_lead_crm.customer_name),
    customer_phone = coalesce(excluded.customer_phone, public.imobagent_20260504_ready_lead_crm.customer_phone),
    contact_id = coalesce(excluded.contact_id, public.imobagent_20260504_ready_lead_crm.contact_id),
    interest_type = coalesce(excluded.interest_type, public.imobagent_20260504_ready_lead_crm.interest_type),
    lead_stage = coalesce(excluded.lead_stage, public.imobagent_20260504_ready_lead_crm.lead_stage),
    lead_temperature = coalesce(excluded.lead_temperature, public.imobagent_20260504_ready_lead_crm.lead_temperature),
    lead_score = coalesce(excluded.lead_score, public.imobagent_20260504_ready_lead_crm.lead_score),
    desired_property_type = coalesce(excluded.desired_property_type, public.imobagent_20260504_ready_lead_crm.desired_property_type),
    desired_city = coalesce(excluded.desired_city, public.imobagent_20260504_ready_lead_crm.desired_city),
    desired_neighborhoods = case when excluded.desired_neighborhoods <> '[]'::jsonb then excluded.desired_neighborhoods else public.imobagent_20260504_ready_lead_crm.desired_neighborhoods end,
    desired_bedrooms = coalesce(excluded.desired_bedrooms, public.imobagent_20260504_ready_lead_crm.desired_bedrooms),
    desired_parking = coalesce(excluded.desired_parking, public.imobagent_20260504_ready_lead_crm.desired_parking),
    budget_max = coalesce(excluded.budget_max, public.imobagent_20260504_ready_lead_crm.budget_max),
    monthly_income = coalesce(excluded.monthly_income, public.imobagent_20260504_ready_lead_crm.monthly_income),
    payment_mode = coalesce(excluded.payment_mode, public.imobagent_20260504_ready_lead_crm.payment_mode),
    financing_needed = coalesce(excluded.financing_needed, public.imobagent_20260504_ready_lead_crm.financing_needed),
    fgts_available = coalesce(excluded.fgts_available, public.imobagent_20260504_ready_lead_crm.fgts_available),
    estimated_down_payment = coalesce(excluded.estimated_down_payment, public.imobagent_20260504_ready_lead_crm.estimated_down_payment),
    urgency = coalesce(excluded.urgency, public.imobagent_20260504_ready_lead_crm.urgency),
    pain_point = coalesce(excluded.pain_point, public.imobagent_20260504_ready_lead_crm.pain_point),
    objections = coalesce(excluded.objections, public.imobagent_20260504_ready_lead_crm.objections),
    matched_listings = case when excluded.matched_listings <> '[]'::jsonb then excluded.matched_listings else public.imobagent_20260504_ready_lead_crm.matched_listings end,
    favorite_listing = coalesce(excluded.favorite_listing, public.imobagent_20260504_ready_lead_crm.favorite_listing),
    visit_interest = coalesce(excluded.visit_interest, public.imobagent_20260504_ready_lead_crm.visit_interest),
    visit_status = coalesce(excluded.visit_status, public.imobagent_20260504_ready_lead_crm.visit_status),
    seller_owner = coalesce(excluded.seller_owner, public.imobagent_20260504_ready_lead_crm.seller_owner),
    assigned_seller = coalesce(excluded.assigned_seller, public.imobagent_20260504_ready_lead_crm.assigned_seller),
    handoff_status = coalesce(excluded.handoff_status, public.imobagent_20260504_ready_lead_crm.handoff_status),
    next_best_action = coalesce(excluded.next_best_action, public.imobagent_20260504_ready_lead_crm.next_best_action),
    conversation_summary = coalesce(excluded.conversation_summary, public.imobagent_20260504_ready_lead_crm.conversation_summary),
    seller_summary = coalesce(excluded.seller_summary, public.imobagent_20260504_ready_lead_crm.seller_summary),
    last_inbound_text = coalesce(excluded.last_inbound_text, public.imobagent_20260504_ready_lead_crm.last_inbound_text),
    last_outbound_text = coalesce(excluded.last_outbound_text, public.imobagent_20260504_ready_lead_crm.last_outbound_text),
    last_inbound_at = coalesce(excluded.last_inbound_at, public.imobagent_20260504_ready_lead_crm.last_inbound_at),
    last_outbound_at = coalesce(excluded.last_outbound_at, public.imobagent_20260504_ready_lead_crm.last_outbound_at),
    updated_at = now();

  return jsonb_build_object('ok', true, 'phone_e164', v_phone, 'lead_stage', p_lead_stage, 'lead_temperature', p_lead_temperature);
end;
$$;

create or replace function public.imobagent_20260504_ready_admin_summary_today_realty(
  p_tenant_id text default 'default'
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tenant text := coalesce(nullif(p_tenant_id, ''), 'default');
  v_from timestamptz := date_trunc('day', now() at time zone 'America/Sao_Paulo') at time zone 'America/Sao_Paulo';
  v_to timestamptz := v_from + interval '1 day';
  v_result jsonb;
begin
  select jsonb_build_object(
    'tenant_id', v_tenant,
    'leads_today', (select count(*) from public.imobagent_20260504_ready_customers c where c.tenant_id = v_tenant and c.created_at >= v_from and c.created_at < v_to),
    'leads_received', (select count(distinct e.phone_e164) from public.imobagent_20260504_ready_conversation_events e where e.tenant_id = v_tenant and e.created_at >= v_from and e.created_at < v_to and e.phone_e164 is not null),
    'hot_today', (select count(*) from public.imobagent_20260504_ready_lead_crm l where l.tenant_id = v_tenant and l.updated_at >= v_from and l.updated_at < v_to and (lower(coalesce(l.lead_temperature,'')) = 'quente' or coalesce(l.lead_score,0) >= 70)),
    'visits_interest_today', (select count(*) from public.imobagent_20260504_ready_lead_crm l where l.tenant_id = v_tenant and l.updated_at >= v_from and l.updated_at < v_to and coalesce(l.visit_interest,false) = true),
    'visits_requested', (select count(*) from public.imobagent_20260504_ready_appointments a where a.tenant_id = v_tenant and a.created_at >= v_from and a.created_at < v_to),
    'handoffs_today', (select count(*) from public.imobagent_20260504_ready_handoffs h where h.tenant_id = v_tenant and h.created_at >= v_from and h.created_at < v_to),
    'awaiting_seller', (select count(*) from public.imobagent_20260504_ready_handoffs h where h.tenant_id = v_tenant and h.status = 'queued'),
    'queued_handoffs', (select count(*) from public.imobagent_20260504_ready_handoffs h where h.tenant_id = v_tenant and h.status = 'queued'),
    'leads_sem_resposta', (select count(*) from public.imobagent_20260504_ready_lead_crm l where l.tenant_id = v_tenant and l.last_outbound_at is not null and l.updated_at < now() - interval '2 hours'),
    'top_regions', (
      select coalesce(jsonb_agg(jsonb_build_object('region', region, 'count', cnt)), '[]'::jsonb)
      from (
        select coalesce(nullif(l.desired_city,''), nullif(l.desired_neighborhoods->>0,''), 'sem região') as region, count(*) cnt
        from public.imobagent_20260504_ready_lead_crm l
        where l.tenant_id = v_tenant and l.updated_at >= v_from and l.updated_at < v_to
        group by 1 order by 2 desc limit 5
      ) s
    ),
    'top_listings', (
      select coalesce(jsonb_agg(jsonb_build_object('listing', listing, 'count', cnt)), '[]'::jsonb)
      from (
        select coalesce(nullif(l.favorite_listing,''), l.matched_listings->>0, 'sem imóvel') as listing, count(*) cnt
        from public.imobagent_20260504_ready_lead_crm l
        where l.tenant_id = v_tenant and l.updated_at >= v_from and l.updated_at < v_to
        group by 1 order by 2 desc limit 5
      ) s
    )
  ) into v_result;

  return v_result;
end;
$$;

create or replace function public.imobagent_20260504_ready_admin_summary_week_realty(
  p_tenant_id text default 'default'
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tenant text := coalesce(nullif(p_tenant_id, ''), 'default');
  v_from timestamptz := now() - interval '7 days';
  v_result jsonb;
begin
  select jsonb_build_object(
    'tenant_id', v_tenant,
    'leads_today', (select count(*) from public.imobagent_20260504_ready_customers c where c.tenant_id = v_tenant and c.created_at >= v_from),
    'leads_received', (select count(distinct e.phone_e164) from public.imobagent_20260504_ready_conversation_events e where e.tenant_id = v_tenant and e.created_at >= v_from and e.phone_e164 is not null),
    'hot_today', (select count(*) from public.imobagent_20260504_ready_lead_crm l where l.tenant_id = v_tenant and l.updated_at >= v_from and (lower(coalesce(l.lead_temperature,'')) = 'quente' or coalesce(l.lead_score,0) >= 70)),
    'visits_interest_today', (select count(*) from public.imobagent_20260504_ready_lead_crm l where l.tenant_id = v_tenant and l.updated_at >= v_from and coalesce(l.visit_interest,false) = true),
    'visits_requested', (select count(*) from public.imobagent_20260504_ready_appointments a where a.tenant_id = v_tenant and a.created_at >= v_from),
    'handoffs_today', (select count(*) from public.imobagent_20260504_ready_handoffs h where h.tenant_id = v_tenant and h.created_at >= v_from),
    'awaiting_seller', (select count(*) from public.imobagent_20260504_ready_handoffs h where h.tenant_id = v_tenant and h.status = 'queued'),
    'queued_handoffs', (select count(*) from public.imobagent_20260504_ready_handoffs h where h.tenant_id = v_tenant and h.status = 'queued'),
    'leads_sem_resposta', (select count(*) from public.imobagent_20260504_ready_lead_crm l where l.tenant_id = v_tenant and l.last_outbound_at is not null and l.updated_at < now() - interval '2 hours'),
    'top_regions', (
      select coalesce(jsonb_agg(jsonb_build_object('region', region, 'count', cnt)), '[]'::jsonb)
      from (
        select coalesce(nullif(l.desired_city,''), nullif(l.desired_neighborhoods->>0,''), 'sem região') as region, count(*) cnt
        from public.imobagent_20260504_ready_lead_crm l
        where l.tenant_id = v_tenant and l.updated_at >= v_from
        group by 1 order by 2 desc limit 5
      ) s
    ),
    'top_listings', (
      select coalesce(jsonb_agg(jsonb_build_object('listing', listing, 'count', cnt)), '[]'::jsonb)
      from (
        select coalesce(nullif(l.favorite_listing,''), l.matched_listings->>0, 'sem imóvel') as listing, count(*) cnt
        from public.imobagent_20260504_ready_lead_crm l
        where l.tenant_id = v_tenant and l.updated_at >= v_from
        group by 1 order by 2 desc limit 5
      ) s
    )
  ) into v_result;

  return v_result;
end;
$$;

create or replace function public.imobagent_20260504_ready_admin_operational_alerts(
  p_tenant_id text default 'default'
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tenant text := coalesce(nullif(p_tenant_id, ''), 'default');
  v_oldest numeric;
begin
  select extract(epoch from (now() - min(created_at))) / 60
  into v_oldest
  from public.imobagent_20260504_ready_handoffs
  where tenant_id = v_tenant and status = 'queued';

  return jsonb_build_object(
    'tenant_id', v_tenant,
    'queued_handoffs', (select count(*) from public.imobagent_20260504_ready_handoffs where tenant_id = v_tenant and status = 'queued'),
    'oldest_queued_handoff_minutes', coalesce(round(v_oldest), 0),
    'sla_overdue', (select count(*) from public.imobagent_20260504_ready_handoffs where tenant_id = v_tenant and status = 'queued' and created_at < now() - interval '10 minutes'),
    'pending_followups', (select count(*) from public.imobagent_20260504_ready_lead_crm where tenant_id = v_tenant and last_outbound_at is not null and updated_at < now() - interval '3 hours'),
    'pending_confirmations', (select count(*) from public.imobagent_20260504_ready_appointments where tenant_id = v_tenant and status in ('booked','rescheduled') and start_at between now() and now() + interval '24 hours')
  );
end;
$$;

create or replace function public.imobagent_20260504_ready_admin_followup_queue(
  p_tenant_id text default 'default'
) returns table (
  queue_type text,
  phone_e164 text,
  customer_name text,
  lead_stage text,
  lead_temperature text,
  favorite_listing text,
  last_outbound_at timestamptz,
  updated_at timestamptz,
  priority numeric
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tenant text := coalesce(nullif(p_tenant_id, ''), 'default');
begin
  return query
  select
    q.queue_type,
    q.phone_e164,
    q.customer_name,
    q.lead_stage,
    q.lead_temperature,
    q.favorite_listing,
    q.last_outbound_at,
    q.updated_at,
    q.priority
  from (
    select
      case
        when coalesce(l.visit_interest,false) = true and coalesce(l.visit_status,'') not in ('booked','rescheduled','confirmed','confirmed_24h') then 'agendamento_abandonado'
        when coalesce(l.handoff_status,'') = 'queued' or lower(coalesce(l.lead_temperature,'')) = 'quente' then 'orcamentos_sem_fechamento'
        when l.updated_at < now() - interval '60 days' then 'inativos_60d'
        else 'aguardando_resposta'
      end as queue_type,
      l.phone_e164,
      l.customer_name,
      l.lead_stage,
      l.lead_temperature,
      l.favorite_listing,
      l.last_outbound_at,
      l.updated_at,
      case
        when lower(coalesce(l.lead_temperature,'')) = 'quente' then 90
        when coalesce(l.visit_interest,false) = true then 70
        when coalesce(l.lead_score,0) >= 45 then 50
        else 20
      end as priority
    from public.imobagent_20260504_ready_lead_crm l
    where l.tenant_id = v_tenant
      and l.updated_at < now() - interval '30 minutes'
  ) q
  order by q.priority desc, q.updated_at asc
  limit 100;
end;
$$;


-- ============================================================
-- SQL COMPLEMENTAR DE PRODUCAO v1 corrigido
-- ============================================================

-- Lais Imob Pro v1.0 | SQL complementar de produção
-- Seguro e não destrutivo. Não remove dados e não altera objetos fora dos prefixos imobagent_* / imobagent_20260504_ready_*.
-- Execute depois do arquivo 01_BASE_ORIGINAL_SEGURA.sql.
-- Objetivo: idempotência persistente, lock atômico de agenda, comandos de corretor, catálogo runtime, log de erro e commits mais seguros.

create extension if not exists pgcrypto;

-- 1) Idempotência persistente inbound
create table if not exists public.imobagent_inbound_idempotency (
  id uuid primary key default gen_random_uuid(),
  tenant_id text not null default 'default',
  idempotency_key text not null,
  contact_key text,
  message_uid text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (tenant_id, idempotency_key)
);
create index if not exists imobagent_inbound_idempotency_created_idx on public.imobagent_inbound_idempotency (tenant_id, created_at desc);

create or replace function public.imobagent_try_register_inbound(
  p_tenant_id text default 'default',
  p_idempotency_key text default null,
  p_contact_key text default null,
  p_message_uid text default null,
  p_payload jsonb default '{}'::jsonb
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tenant text := coalesce(nullif(p_tenant_id, ''), 'default');
  v_key text := nullif(p_idempotency_key, '');
  v_id uuid;
begin
  if v_key is null then
    return jsonb_build_object('ok', true, 'registered', false, 'reason', 'missing_idempotency_key_passthrough');
  end if;

  insert into public.imobagent_inbound_idempotency (tenant_id, idempotency_key, contact_key, message_uid, payload)
  values (v_tenant, v_key, nullif(p_contact_key, ''), nullif(p_message_uid, ''), coalesce(p_payload, '{}'::jsonb))
  on conflict (tenant_id, idempotency_key) do nothing
  returning id into v_id;

  if v_id is null then
    return jsonb_build_object('ok', false, 'duplicate', true, 'reason', 'duplicate_inbound_message', 'tenant_id', v_tenant, 'idempotency_key', v_key);
  end if;

  return jsonb_build_object('ok', true, 'registered', true, 'duplicate', false, 'tenant_id', v_tenant, 'idempotency_key', v_key, 'id', v_id);
end;
$$;

-- 2) Idempotência persistente outbound
create table if not exists public.imobagent_outbound_idempotency (
  id uuid primary key default gen_random_uuid(),
  tenant_id text not null default 'default',
  idempotency_key text not null,
  contact_key text,
  channel text default 'whatsapp',
  outbound_text text,
  provider_response jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (tenant_id, idempotency_key)
);
create index if not exists imobagent_outbound_idempotency_created_idx on public.imobagent_outbound_idempotency (tenant_id, created_at desc);

create or replace function public.imobagent_try_register_outbound(
  p_tenant_id text default 'default',
  p_idempotency_key text default null,
  p_contact_key text default null,
  p_channel text default 'whatsapp',
  p_outbound_text text default null,
  p_provider_response jsonb default '{}'::jsonb
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tenant text := coalesce(nullif(p_tenant_id, ''), 'default');
  v_key text := nullif(p_idempotency_key, '');
  v_id uuid;
begin
  if v_key is null then
    return jsonb_build_object('ok', true, 'registered', false, 'reason', 'missing_idempotency_key_passthrough');
  end if;

  insert into public.imobagent_outbound_idempotency (tenant_id, idempotency_key, contact_key, channel, outbound_text, provider_response)
  values (v_tenant, v_key, nullif(p_contact_key, ''), coalesce(nullif(p_channel, ''), 'whatsapp'), p_outbound_text, coalesce(p_provider_response, '{}'::jsonb))
  on conflict (tenant_id, idempotency_key) do nothing
  returning id into v_id;

  if v_id is null then
    return jsonb_build_object('ok', false, 'duplicate', true, 'reason', 'duplicate_outbound_message', 'tenant_id', v_tenant, 'idempotency_key', v_key);
  end if;

  return jsonb_build_object('ok', true, 'registered', true, 'duplicate', false, 'tenant_id', v_tenant, 'idempotency_key', v_key, 'id', v_id);
end;
$$;

-- 3) Lock atômico de agenda
create table if not exists public.imobagent_20260504_ready_slot_locks (
  lock_id uuid primary key default gen_random_uuid(),
  tenant_id text not null default 'default',
  slot_key text not null,
  calendar_id text,
  start_at timestamptz,
  end_at timestamptz,
  phone_e164 text,
  service_key text,
  action text default 'book',
  idempotency_key text,
  trace_id text,
  lock_token text not null default encode(gen_random_bytes(18), 'hex'),
  status text not null default 'locked',
  expires_at timestamptz not null default now() + interval '10 minutes',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists imobagent_ready_slot_locks_active_uniq
  on public.imobagent_20260504_ready_slot_locks (tenant_id, slot_key)
  where status = 'locked';
create index if not exists imobagent_ready_slot_locks_expiry_idx
  on public.imobagent_20260504_ready_slot_locks (tenant_id, status, expires_at);

create or replace function public.imobagent_20260504_ready_acquire_slot_lock(
  p_slot_key text default null,
  p_phone_e164 text default null,
  p_action text default 'book',
  p_service_key text default null,
  p_start_at timestamptz default null,
  p_end_at timestamptz default null,
  p_calendar_id text default 'primary',
  p_tenant_id text default 'default',
  p_trace_id text default null,
  p_idempotency_key text default null,
  p_ttl_seconds integer default 600
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tenant text := coalesce(nullif(p_tenant_id, ''), 'default');
  v_slot_key text := coalesce(nullif(p_slot_key, ''), coalesce(nullif(p_calendar_id, ''), 'primary') || '|' || coalesce(p_start_at::text, '') || '|' || coalesce(p_end_at::text, ''));
  v_lock public.imobagent_20260504_ready_slot_locks%rowtype;
  v_ttl integer := greatest(coalesce(p_ttl_seconds, 600), 60);
begin
  update public.imobagent_20260504_ready_slot_locks
     set status = 'expired', updated_at = now()
   where tenant_id = v_tenant and status = 'locked' and expires_at <= now();

  insert into public.imobagent_20260504_ready_slot_locks (
    tenant_id, slot_key, calendar_id, start_at, end_at, phone_e164, service_key,
    action, idempotency_key, trace_id, expires_at, metadata
  ) values (
    v_tenant, v_slot_key, nullif(p_calendar_id, ''), p_start_at, p_end_at, p_phone_e164, p_service_key,
    coalesce(nullif(p_action, ''), 'book'), nullif(p_idempotency_key, ''), nullif(p_trace_id, ''),
    now() + make_interval(secs => v_ttl), jsonb_build_object('source', 'acquire_slot_lock_v1')
  )
  on conflict do nothing
  returning * into v_lock;

  if v_lock.lock_id is null then
    return jsonb_build_object('ok', false, 'lock_acquired', false, 'acquired', false, 'status', 'busy', 'reason', 'slot_locked', 'tenant_id', v_tenant, 'slot_key', v_slot_key);
  end if;

  return jsonb_build_object(
    'ok', true, 'lock_acquired', true, 'acquired', true, 'status', 'ok',
    'tenant_id', v_tenant, 'slot_key', v_lock.slot_key, 'lock_token', v_lock.lock_token,
    'booking_lock_token', v_lock.lock_token, 'expires_at', v_lock.expires_at,
    'start_at', v_lock.start_at, 'end_at', v_lock.end_at
  );
end;
$$;

create or replace function public.imobagent_20260504_ready_release_slot_lock(
  p_tenant_id text default 'default',
  p_slot_key text default null,
  p_lock_token text default null,
  p_status text default 'released'
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tenant text := coalesce(nullif(p_tenant_id, ''), 'default');
  v_count integer;
begin
  update public.imobagent_20260504_ready_slot_locks
     set status = coalesce(nullif(p_status, ''), 'released'), updated_at = now()
   where tenant_id = v_tenant
     and status = 'locked'
     and (p_slot_key is null or slot_key = p_slot_key)
     and (p_lock_token is null or lock_token = p_lock_token);
  get diagnostics v_count = row_count;
  return jsonb_build_object('ok', true, 'released_count', v_count, 'tenant_id', v_tenant);
end;
$$;

-- 4) Commit de agendamento com validação de conflito e liberação de lock
create or replace function public.imobagent_20260504_ready_commit_book(
  p_slot_key text default null,
  p_event_id text default null,
  p_phone_e164 text default null,
  p_customer_name text default null,
  p_calendar_id text default null,
  p_service_key text default null,
  p_service_label text default null,
  p_date_br text default null,
  p_time_hhmm text default null,
  p_start_at timestamptz default null,
  p_end_at timestamptz default null,
  p_lead_score numeric default null,
  p_lead_category text default null,
  p_tenant_id text default 'default',
  p_trace_id text default null,
  p_idempotency_key text default null,
  p_lock_token text default null,
  p_release_lock boolean default true
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tenant text := coalesce(nullif(p_tenant_id, ''), 'default');
  v_appt_id text := coalesce(nullif(p_idempotency_key, ''), nullif(p_event_id, ''), 'appt_' || md5(coalesce(p_phone_e164,'') || coalesce(p_service_key,'') || coalesce(p_start_at::text, now()::text)));
  v_conflict text;
begin
  select appointment_id into v_conflict
  from public.imobagent_20260504_ready_appointments
  where tenant_id = v_tenant
    and coalesce(calendar_id,'primary') = coalesce(p_calendar_id,'primary')
    and start_at = p_start_at
    and status in ('booked', 'rescheduled', 'confirmed', 'confirmed_24h')
    and appointment_id <> v_appt_id
  limit 1;

  if v_conflict is not null then
    return jsonb_build_object('ok', false, 'reason', 'slot_already_booked', 'conflicting_appointment_id', v_conflict, 'status', 'busy');
  end if;

  insert into public.imobagent_20260504_ready_appointments (
    tenant_id, appointment_id, phone_e164, customer_name, calendar_id, calendar_event_id,
    service_key, service_label, date_br, time_hhmm, start_at, end_at, status,
    lead_score, lead_category, metadata, updated_at
  ) values (
    v_tenant, v_appt_id, p_phone_e164, p_customer_name, p_calendar_id, p_event_id,
    p_service_key, p_service_label, p_date_br, p_time_hhmm, p_start_at, p_end_at, 'booked',
    p_lead_score, p_lead_category, jsonb_build_object('slot_key', p_slot_key, 'trace_id', p_trace_id, 'lock_token', p_lock_token), now()
  )
  on conflict (tenant_id, appointment_id) do update set
    calendar_event_id = coalesce(excluded.calendar_event_id, public.imobagent_20260504_ready_appointments.calendar_event_id),
    status = 'booked',
    start_at = coalesce(excluded.start_at, public.imobagent_20260504_ready_appointments.start_at),
    end_at = coalesce(excluded.end_at, public.imobagent_20260504_ready_appointments.end_at),
    updated_at = now();

  if coalesce(p_release_lock, true) then
    perform public.imobagent_20260504_ready_release_slot_lock(v_tenant, p_slot_key, p_lock_token, 'committed');
  end if;

  return jsonb_build_object('ok', true, 'appointment_id', v_appt_id, 'status', 'booked');
end;
$$;

create or replace function public.imobagent_20260504_ready_commit_reschedule(
  p_slot_key text default null,
  p_old_event_id text default null,
  p_new_event_id text default null,
  p_phone_e164 text default null,
  p_customer_name text default null,
  p_calendar_id text default null,
  p_service_key text default null,
  p_service_label text default null,
  p_date_br text default null,
  p_time_hhmm text default null,
  p_start_at timestamptz default null,
  p_end_at timestamptz default null,
  p_delete_old_success boolean default true,
  p_delete_old_error text default null,
  p_tenant_id text default 'default',
  p_trace_id text default null,
  p_idempotency_key text default null,
  p_lock_token text default null,
  p_release_lock boolean default true
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tenant text := coalesce(nullif(p_tenant_id, ''), 'default');
  v_appt_id text := coalesce(nullif(p_idempotency_key, ''), nullif(p_new_event_id, ''), 'appt_' || md5(coalesce(p_phone_e164,'') || coalesce(p_service_key,'') || coalesce(p_start_at::text, now()::text)));
  v_conflict text;
begin
  select appointment_id into v_conflict
  from public.imobagent_20260504_ready_appointments
  where tenant_id = v_tenant
    and coalesce(calendar_id,'primary') = coalesce(p_calendar_id,'primary')
    and start_at = p_start_at
    and status in ('booked', 'rescheduled', 'confirmed', 'confirmed_24h')
    and appointment_id <> v_appt_id
  limit 1;

  if v_conflict is not null then
    return jsonb_build_object('ok', false, 'reason', 'slot_already_booked', 'conflicting_appointment_id', v_conflict, 'status', 'busy');
  end if;

  update public.imobagent_20260504_ready_appointments
     set status = 'rescheduled_old', updated_at = now(), metadata = coalesce(metadata,'{}'::jsonb) || jsonb_build_object('new_event_id', p_new_event_id, 'delete_old_success', p_delete_old_success, 'delete_old_error', p_delete_old_error)
   where tenant_id = v_tenant and calendar_event_id = p_old_event_id;

  insert into public.imobagent_20260504_ready_appointments (
    tenant_id, appointment_id, phone_e164, customer_name, calendar_id, calendar_event_id,
    service_key, service_label, date_br, time_hhmm, start_at, end_at, status,
    metadata, updated_at
  ) values (
    v_tenant, v_appt_id, p_phone_e164, p_customer_name, p_calendar_id, p_new_event_id,
    p_service_key, p_service_label, p_date_br, p_time_hhmm, p_start_at, p_end_at, 'rescheduled',
    jsonb_build_object('slot_key', p_slot_key, 'trace_id', p_trace_id, 'lock_token', p_lock_token, 'old_event_id', p_old_event_id), now()
  )
  on conflict (tenant_id, appointment_id) do update set
    calendar_event_id = coalesce(excluded.calendar_event_id, public.imobagent_20260504_ready_appointments.calendar_event_id),
    status = 'rescheduled',
    start_at = coalesce(excluded.start_at, public.imobagent_20260504_ready_appointments.start_at),
    end_at = coalesce(excluded.end_at, public.imobagent_20260504_ready_appointments.end_at),
    updated_at = now();

  if coalesce(p_release_lock, true) then
    perform public.imobagent_20260504_ready_release_slot_lock(v_tenant, p_slot_key, p_lock_token, 'committed');
  end if;

  return jsonb_build_object('ok', true, 'appointment_id', v_appt_id, 'status', 'rescheduled', 'delete_old_success', p_delete_old_success);
end;
$$;

-- 5) Comandos de corretor/admin
create table if not exists public.imobagent_20260504_ready_seller_commands (
  command_id bigint generated by default as identity primary key,
  tenant_id text not null default 'default',
  phone_e164 text,
  command text,
  status text default 'received',
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists imobagent_ready_seller_commands_tenant_created_idx on public.imobagent_20260504_ready_seller_commands (tenant_id, created_at desc);

create or replace function public.imobagent_20260504_ready_record_seller_command(
  p_payload jsonb default '{}'::jsonb,
  p_tenant_id text default 'default'
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tenant text := coalesce(nullif(p_tenant_id, ''), coalesce(p_payload->>'tenant_id', 'default'));
  v_id bigint;
  v_phone text := coalesce(p_payload->>'phone_e164', p_payload->>'customer_phone', p_payload->>'seller_phone');
  v_command text := coalesce(p_payload->>'command', p_payload->>'normalized_command', p_payload->>'action');
begin
  insert into public.imobagent_20260504_ready_seller_commands (tenant_id, phone_e164, command, status, payload)
  values (v_tenant, v_phone, v_command, 'received', coalesce(p_payload, '{}'::jsonb))
  returning command_id into v_id;

  return jsonb_build_object('ok', true, 'command_id', v_id, 'tenant_id', v_tenant, 'status', 'received');
end;
$$;

-- 6) Catálogo runtime opcional pelo Supabase
create or replace function public.imobagent_20260504_ready_catalog_export(
  p_tenant_id text default 'default',
  p_only_active boolean default true
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tenant text := coalesce(nullif(p_tenant_id, ''), 'default');
  v_config jsonb;
  v_services jsonb;
begin
  select config into v_config
  from public.imobagent_20260504_ready_runtime_config
  where tenant_id = v_tenant;

  v_services := coalesce(v_config->'Services', v_config->'Inventory', v_config->'Catalog', '{}'::jsonb);

  return jsonb_build_object(
    'ok', true,
    'tenant_id', v_tenant,
    'Services', coalesce(v_services, '{}'::jsonb),
    'CatalogSource', 'supabase_runtime_config',
    'only_active', coalesce(p_only_active, true)
  );
end;
$$;

-- 7) Log operacional para alertas/painel
create table if not exists public.imobagent_20260504_ready_operational_errors (
  error_id bigint generated by default as identity primary key,
  tenant_id text not null default 'default',
  workflow_name text,
  execution_id text,
  node_name text,
  error_message text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists imobagent_ready_errors_tenant_created_idx on public.imobagent_20260504_ready_operational_errors (tenant_id, created_at desc);

create or replace function public.imobagent_20260504_ready_log_error(
  p_tenant_id text default 'default',
  p_workflow_name text default null,
  p_execution_id text default null,
  p_node_name text default null,
  p_error_message text default null,
  p_payload jsonb default '{}'::jsonb
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id bigint;
begin
  insert into public.imobagent_20260504_ready_operational_errors (tenant_id, workflow_name, execution_id, node_name, error_message, payload)
  values (coalesce(nullif(p_tenant_id,''),'default'), p_workflow_name, p_execution_id, p_node_name, p_error_message, coalesce(p_payload,'{}'::jsonb))
  returning error_id into v_id;
  return jsonb_build_object('ok', true, 'error_id', v_id);
end;
$$;

-- 8) Índices auxiliares não destrutivos
create index if not exists imobagent_ready_customers_tenant_updated_idx on public.imobagent_20260504_ready_customers (tenant_id, updated_at desc);
create index if not exists imobagent_ready_appointments_tenant_start_idx on public.imobagent_20260504_ready_appointments (tenant_id, calendar_id, start_at desc);

-- Fim do SQL complementar v1.0.
